# Generated by Django 3.1 on 2020-08-27 16:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_code', models.CharField(max_length=50, unique=True, verbose_name='Activity Ref')),
                ('activity_description', models.CharField(max_length=255, verbose_name='Activity Description')),
                ('labour_base', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Fixed Contract Labour')),
                ('labour_uplift', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Labour Uplift')),
                ('labour_total', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Labour Total')),
                ('materials_other', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='NEMS')),
                ('total_payable', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Total Payable')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_description', models.CharField(max_length=25, verbose_name='Unit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_number', models.SmallIntegerField(unique=True, verbose_name='Application No')),
                ('app_date', models.DateField(verbose_name='Application Date')),
                ('app_ref', models.CharField(max_length=255, verbose_name='Application Ref')),
                ('app_open', models.BooleanField(verbose_name='Application Open')),
                ('app_current', models.BooleanField(verbose_name='Current Application')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_code', models.CharField(max_length=1, verbose_name='Region Code')),
                ('area_description', models.CharField(max_length=255, verbose_name='Region')),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construction_image', models.ImageField(blank=True, upload_to='images/', verbose_name='Construction Image')),
                ('image_type', models.CharField(choices=[('PRE', 'Pre Construction Image'), ('MISC', 'Misc Construction Image'), ('POST', 'Post Construction Image')], max_length=10, verbose_name='Image Type')),
                ('date_image', models.DateField(blank=True, null=True, verbose_name='Image Date')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.IntegerField(null=True, verbose_name='Item Number')),
                ('item_type', models.CharField(choices=[('BOQ', 'BOQ'), ('VARN', 'Variation'), ('MISC', 'Misc')], default='BOQ', max_length=10, null=True)),
                ('qty_ordered', models.DecimalField(blank=True, decimal_places=4, default=1, max_digits=12, null=True, verbose_name='Qty')),
                ('labour_base', models.DecimalField(decimal_places=4, default=0, max_digits=12, null=True)),
                ('labour_uplift', models.DecimalField(decimal_places=4, default=0, max_digits=12, null=True)),
                ('labour_total', models.DecimalField(decimal_places=4, default=0, max_digits=12, null=True)),
                ('unit_labour_payable', models.DecimalField(decimal_places=4, default=0, max_digits=12, null=True, verbose_name='Unit Labour Payable')),
                ('materials_base', models.DecimalField(decimal_places=4, default=0, max_digits=12, null=True)),
                ('materials_uplift', models.DecimalField(decimal_places=4, default=0, max_digits=12, null=True)),
                ('materials_total_excl_other_materials', models.DecimalField(decimal_places=4, default=0, max_digits=12, null=True, verbose_name='Material Pack Total')),
                ('materials_other', models.DecimalField(decimal_places=4, default=0, max_digits=12, null=True)),
                ('materials_total_incl_other_materials', models.DecimalField(decimal_places=4, default=0, max_digits=12, null=True)),
                ('unit_materials_payable', models.DecimalField(decimal_places=4, default=0, max_digits=12, null=True, verbose_name='Unit Materials Payable')),
                ('total_payable', models.DecimalField(decimal_places=4, default=0, max_digits=12, null=True)),
                ('unit_total_payable', models.DecimalField(decimal_places=4, default=0, max_digits=12, null=True, verbose_name='Unit Total Payable')),
                ('pack_number', models.CharField(blank=True, max_length=255, null=True)),
                ('item_status', models.CharField(default='Open', max_length=20, verbose_name='Item Status')),
                ('item_complete', models.BooleanField(default=False, verbose_name='Item Complete')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('activity_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_orders.activity')),
            ],
        ),
        migrations.CreateModel(
            name='OrderHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_instruction', models.IntegerField(unique=True, verbose_name='Work Instruction')),
                ('job_number', models.CharField(max_length=50, verbose_name='Job Number')),
                ('project_title', models.CharField(max_length=255, verbose_name='Project Title')),
                ('project_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('end_date', models.DateField(default=datetime.datetime.now)),
                ('issued_date', models.DateField(default=datetime.datetime.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('document_1', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='H&S Pack')),
                ('document_2', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Field Docs')),
                ('document_3', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Field Docs')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_orders.area', verbose_name='Area')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_description', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_ref', models.CharField(max_length=255, verbose_name='Pole Number')),
                ('location_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('worksheet_ref', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Worksheet Ref')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('construction_image', models.ManyToManyField(blank=True, to='work_orders.ConstructionImage', verbose_name='Construction Image')),
                ('work_instruction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='work_orders.orderheader', to_field='work_instruction', verbose_name='Work Instruction')),
            ],
            options={
                'unique_together': {('work_instruction', 'location_ref')},
            },
        ),
        migrations.CreateModel(
            name='SuperVisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('surname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type_description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Work Type')),
            ],
        ),
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_work_done', models.DateField(blank=True, null=True, verbose_name='Work Done Date')),
                ('qty_complete', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Qty Complete')),
                ('value_complete', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Value Complete')),
                ('materials_complete', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Materials Complete')),
                ('labour_complete', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Labour Complete')),
                ('applied', models.BooleanField(default=False, verbose_name='Applied For')),
                ('application_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='work_orders.application', to_field='app_number')),
                ('completed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='work_orders.supervisor', verbose_name='Supervisor')),
                ('item_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='work_orders.orderdetail', verbose_name='Item')),
                ('worksheet_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_orders.sitelocation', verbose_name='Location Ref')),
            ],
        ),
        migrations.AddField(
            model_name='orderheader',
            name='project_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='work_orders.orderstatus'),
        ),
        migrations.AddField(
            model_name='orderheader',
            name='project_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='work_orders.worktype', verbose_name='Job Type'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='location_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='work_orders.sitelocation', verbose_name='Pole Number'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='work_instruction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='work_orders.orderheader', to_field='work_instruction'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construction_image', models.ImageField(blank=True, upload_to='images/', verbose_name='Construction Image')),
                ('image_type', models.CharField(choices=[('PRE', 'Pre Construction Image'), ('MISC', 'Misc Construction Image'), ('POST', 'Post Construction Image')], max_length=10, verbose_name='Image Type')),
                ('date_image', models.DateField(blank=True, null=True, verbose_name='Image Date')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_orders.sitelocation', verbose_name='Site Location')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='work_orders.activityunits', verbose_name='Unit'),
        ),
        migrations.AlterUniqueTogether(
            name='orderdetail',
            unique_together={('work_instruction', 'item_number')},
        ),
    ]
