# Generated by Django 3.1 on 2020-09-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
