# Generated by Django 3.1 on 2020-09-11 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='date_image',
            field=models.DateField(blank=True, null=True, verbose_name='Image Date'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_type',
            field=models.CharField(choices=[('PRE', 'Pre Construction Image'), ('MISC', 'Misc Construction Image'), ('POST', 'Post Construction Image')], default='PRE', max_length=10, verbose_name='Image Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.ForeignKey(default=3811, on_delete=django.db.models.deletion.PROTECT, to='work_orders.sitelocation', verbose_name='Site Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
