# Generated by Django 3.1 on 2020-09-12 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0004_auto_20200911_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
