# Generated by Django 3.1.1 on 2020-09-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0007_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
