# Generated by Django 3.1.1 on 2020-09-15 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0009_auto_20200912_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('document_title', models.CharField(max_length=100)),
                ('work_instruction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_orders.orderheader')),
            ],
        ),
    ]
