# Generated by Django 3.1.1 on 2020-09-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0010_auto_20200915_1640'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documents',
            new_name='Document',
        ),
    ]
