# Generated by Django 3.1.1 on 2020-09-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0011_auto_20200915_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='construction_image_resized',
            field=models.ImageField(blank=True, upload_to='images/resized/', verbose_name='Resized Construction Image'),
        ),
    ]
