# Generated by Django 3.1.1 on 2020-09-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0012_image_construction_image_resized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='construction_image',
            field=models.ImageField(blank=True, upload_to='images/original', verbose_name='Construction Image'),
        ),
    ]
