# Generated by Django 3.1.1 on 2020-10-09 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0013_auto_20200921_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateSetUplifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rateset_code', models.IntegerField(unique=True, verbose_name='Rate Set Code')),
                ('labour_uplift_percentage', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Labour Percentage Uplift')),
                ('materials_uplift_percentage', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Materials Percentage Uplift')),
                ('date_from', models.DateField(verbose_name='Date Applicable From')),
                ('date_to', models.DateField(verbose_name='Date Applicable To')),
            ],
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='project_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='work_orders.orderstatus'),
        ),
    ]
