# Generated by Django 3.1.2 on 2020-10-18 01:31

from django.db import migrations
import exiffield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0014_auto_20201009_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='exif',
            field=exiffield.fields.ExifField(default={}, editable=False),
        ),
    ]
