# Generated by Django 3.1.2 on 2020-10-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0015_image_exif'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='camera',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='gps_lat',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='gps_long',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
