# Generated by Django 3.1.2 on 2020-10-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0016_auto_20201018_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='gps_date',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
