# Generated by Django 3.1.2 on 2020-10-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0017_image_gps_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='date_time_original',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
