# Generated by Django 3.1.2 on 2020-11-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0019_auto_20201117_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='item_type',
            field=models.CharField(choices=[('BOQ', 'BOQ'), ('VARN', 'Variation'), ('MISC', 'Misc'), ('FREE', 'Free'), ('DIRECTS', 'Directs')], default='BOQ', max_length=10, null=True),
        ),
    ]
