# Generated by Django 3.1.3 on 2020-11-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0020_auto_20201117_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='gps_position',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
