# Generated by Django 3.1.3 on 2020-11-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0021_image_gps_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderheader',
            name='order_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderheader',
            name='value_applied',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderheader',
            name='value_complete',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
