# Generated by Django 3.1.3 on 2020-12-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0022_auto_20201122_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='iso_week',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='iso_year',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
    ]
