# Generated by Django 3.1.3 on 2020-12-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0023_auto_20201201_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='iso_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='iso_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
