# Generated by Django 3.1.3 on 2020-12-06 02:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0024_auto_20201201_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedApplications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_orders.application')),
            ],
        ),
    ]
