# Generated by Django 3.1.3 on 2020-12-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0027_auto_20201206_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='app_submitted',
            field=models.BooleanField(default=False, verbose_name='Application Submitted'),
        ),
    ]
