# Generated by Django 3.1.3 on 2020-12-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0028_application_app_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='submission_detail',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
