# Generated by Django 3.1.3 on 2020-12-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0029_application_submission_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='submission_detail',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
