# Generated by Django 3.1.3 on 2020-12-06 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0030_auto_20201206_0524'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubmittedApplication',
        ),
    ]
