# Generated by Django 3.1.4 on 2020-12-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0031_delete_submittedapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='iso_date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
