# Generated by Django 3.1.4 on 2020-12-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0032_worksheet_iso_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='iso_year',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
