# Generated by Django 3.1.4 on 2020-12-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0033_auto_20201210_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='iso_date',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='iso_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
