# Generated by Django 3.1.4 on 2020-12-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0034_auto_20201210_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
