# Generated by Django 3.1.4 on 2020-12-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0035_supervisor_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='full_name',
        ),
        migrations.AddField(
            model_name='application',
            name='app_value',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Application Value'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='iso_date',
            field=models.CharField(max_length=8),
        ),
    ]
