# Generated by Django 3.1.4 on 2020-12-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0037_supervisor_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='iso_date',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
