# Generated by Django 3.1.3 on 2020-11-22 21:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_instruction', models.IntegerField(unique=True, verbose_name='Work Instruction')),
                ('job_number', models.CharField(max_length=50, verbose_name='Job Number')),
                ('project_title', models.CharField(max_length=255, verbose_name='Project Title')),
                ('project_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('end_date', models.DateField(default=datetime.datetime.now)),
                ('issued_date', models.DateField(default=datetime.datetime.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.IntegerField(null=True, verbose_name='Item Number')),
                ('item_type', models.CharField(choices=[('BOQ', 'BOQ'), ('VARN', 'Variation'), ('MISC', 'Misc'), ('FREE', 'Free'), ('DIRECTS', 'Directs')], default='BOQ', max_length=10, null=True)),
                ('qty_ordered', models.DecimalField(blank=True, decimal_places=4, default=1, max_digits=12, null=True, verbose_name='Qty')),
                ('labour_base', models.DecimalField(decimal_places=4, default=0, max_digits=12, null=True)),
                ('labour_uplift', models.DecimalField(decimal_places=4, default=0, max_digits=12, null=True)),
                ('labour_total', models.DecimalField(decimal_places=4, default=0, max_digits=12, null=True)),
                ('unit_labour_payable', models.DecimalField(decimal_places=4, default=0, max_digits=12, null=True, verbose_name='Unit Labour Payable')),
                ('materials_base', models.DecimalField(decimal_places=4, default=0, max_digits=12, null=True)),
                ('materials_uplift', models.DecimalField(decimal_places=4, default=0, max_digits=12, null=True)),
                ('materials_total_excl_other_materials', models.DecimalField(decimal_places=4, default=0, max_digits=12, null=True, verbose_name='Material Pack Total')),
                ('materials_other', models.DecimalField(decimal_places=4, default=0, max_digits=12, null=True)),
                ('materials_total_incl_other_materials', models.DecimalField(decimal_places=4, default=0, max_digits=12, null=True)),
                ('unit_materials_payable', models.DecimalField(decimal_places=4, default=0, max_digits=12, null=True, verbose_name='Unit Materials Payable')),
                ('total_payable', models.DecimalField(decimal_places=4, default=0, max_digits=12, null=True)),
                ('unit_total_payable', models.DecimalField(decimal_places=4, default=0, max_digits=12, null=True, verbose_name='Unit Total Payable')),
                ('pack_number', models.CharField(blank=True, max_length=255, null=True)),
                ('item_status', models.CharField(default='Open', max_length=20, verbose_name='Item Status')),
                ('item_complete', models.BooleanField(default=False, verbose_name='Item Complete')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('work_instruction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_data.orderheader', to_field='work_instruction')),
            ],
            options={
                'unique_together': {('work_instruction', 'item_number')},
            },
        ),
    ]
