# Generated by Django 3.1.3 on 2020-11-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_data', '0002_auto_20201122_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderheader',
            name='order_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
